services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27007:27017"
    volumes:
      - "./mongodb:/data/db"
    environment:
      - MONGO_INITDB_USERNAME=&{MONGO_INITDB_USERNAME}
      - MONGO_INITDB_PASSWORD=&{MONGO_INITDB_PASSWORD}
    networks:
      - backend
    restart: always

networks:
  backend: